### ISSUE TITLE
Excess Debugging Info

### ISSUE THREAD

**Issue by radarku** [Protelis/Protelis#198]
We get excessive debugging info from the 11.0.0 release:

```
org.protelis.parser.protelis.impl.LambdaImpl@28501a4b (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@29f85fe1 (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@28f878a0 (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@40e60ece (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@1431267b (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@4b869331 (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@3bdb2c78 (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@2324bfe7 (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@b174a73 (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@29a1505c (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@661d88a (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@24d61e4 (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@36361ddb (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@72825400 (name: ->)
org.protelis.parser.protelis.impl.LambdaImpl@3ab6678b (name: ->)
```

**Comment by jakebeal** [comment]
Can you give a bit more context on what this is coming from?

**Comment by DanySK** [comment]
A leftover println somewhere... I believe #197 solves the problem already.

**Comment by jakebeal** [comment]
@radarku Can you please confirm is this is resolved by release 11.1?

**Comment by jakebeal** [comment]
I'm assigning this to @radarku to confirm resolution.

**Comment by jakebeal** [comment]
Hearing nothing, I'm going to assume this is resolved unless told otherwise.

**Comment by radarku** [comment]
I'm on `protelis-11.1.0+16y.24f6c2a` still getting a bunch of excess debugging from:
```
DefaultLinkingService:105 - before getLinkedObjects: node: ...
DefaultLinkingService:116 - after getLinkedObjects: node: ...
```

**Comment by jakebeal** [comment]
Can you try moving to a more recent release?  The transition from 11 -> 13 should be easier than from 11 -> 12
